<?php

class Erros {
	const ERRO_DESCONHECIDO = 1;
	const ERRO_PARAMETROS_AB = 2;
	const TOKEN_NAO_AUTORIZADO = 3;
	const LOGIN_SENHA_INVALIDA = 4;
	const LOGIN_JA_CADASTRADO = 5;
	const FALHA_REGISTRAR_TOKEN = 6;
	const FALHA_CADASTRAR = 7;
}